### ISSUE TITLE
no PHP?!?!

### ISSUE THREAD

**Issue by didntpot** [RestartFU/learn#1]
WTF men???? NO Hypertext Preprocessor????? >:((

**Comment by RestartFU** [comment]
> WTF men???? NO Hypertext Preprocessor????? >:((

mannn

**Comment by didntpot** [comment]
WTF @RestartFU?? STILL NO PHP >:((( 😡 😡 👿 😡 👿👿

**Comment by RestartFU** [comment]
sorry, but I am not mentally ill

**Comment by didntpot** [comment]
😱
